name: Update blitztactics
on: [push, workflow_dispatch]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run the upgrade script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo sh /home/ubuntu/update.sh
          host: ${{ secrets.HOST1 }} ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY1 }} ${{ secrets.PRIVATE_KEY }}
        env:
          CI: true
      