name: Update blitztactics
on: [push, workflow_dispatch]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run the upgrade script for AZURE CLOUD
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo sh /home/ubuntu/blitz-tactics/update.sh
          host: ${{ secrets.HOST }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY }}
        env:
          CI: true
      - name: Run the upgrade script for AMAZON CLOUD
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo sh /home/ubuntu/blitz-tactics/update.sh
          host: ${{ secrets.HOST1 }}
          username: ubuntu
          privateKey: ${{ secrets.PRIVATE_KEY1 }}
        env:
          CI: true
#       - name: Run the upgrade script for GOOGLE CLOUD
#         uses: garygrossgarten/github-action-ssh@release
#         with:
#           command: sudo sh /home/ubuntu/blitz-tactics/update.sh
#           host: ${{ secrets.HOST2 }}
#           username: ubuntu
#           privateKey: ${{ secrets.PRIVATE_KEY2 }}
#         env:
#           CI: true
      
